
services:
  db:
    image: postgres:9.6
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - "3000:3000"
  

